export const SET_COUNT  =  'SET_COUNT';


export const SET_LOGIN_LOADING  = 'SET_LOGIN_LOADING '
export const SET_LOGIN_SUCCESS  = 'SET_LOGIN_SUCCESS'
export const SET_LOGIN_FAILURE  = 'SET_LOGIN_FAILURE'

export const SET_REG_LOADING  = 'SET_REG_LOADING '
export const SET_REG_SUCCESS  = 'SET_REG_SUCCESS'
export const SET_REG_FAILURE  = 'SET_REG_FAILURE'


export const GET_ALL_PRODUCTS_LOADING  = 'GET_ALL_PRODUCTS_LOADING '
export const GET_ALL_PRODUCTS_SUCCESS  = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAILURE  = 'GET_ALL_PRODUCTS_FAILURE'

export const GET_CART_LOADING  = 'GET_CART_LOADING '
export const GET_CART_SUCCESS  = 'GET_CART_SUCCESS'
export const GET_CART_FAILURE  = 'GET_CART_FAILURE'


export const ADD_TO_CART_LOADING  = 'ADD_TO_CART_LOADING '
export const ADD_TO_CART_SUCCESS  = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAILURE  =  'ADD_TO_CART_FAILURE'

export const CLEAR_A2C_MSG =  'CLEAR_A2C_MSG'





export const LOGOUT  = 'LOGOUT'
export const CLEAN_AUTH =  'CLEAN_AUTH'



